### ISSUE TITLE
ExternalAttrib plugin not loading

### ISSUE THREAD

**Issue by jobar8** [waynegm/OpendTect-5-plugins#8]
I am trying to run the the External Attribute plugin on Windows 7 64bits with OpendTect 5.0.6.
I have copied the dll files as instructed. When I start OdT, the plugin is not in the list. And the new attribute is not in the list of attributes. 
The log file says:
Message from Madagascar.dll:
	RSFROOT not set - no program definitions available

However, I would have thought this plugin does not require Madagascar, or does it?
Thanks for your help.

**Comment by waynegm** [comment]
What about the \*.alo files did they get copied as well? If you are installing into the OpendTect program folder (say __c:\Program Files\opendtect\__)  then:
- the contents of  __bin/win64/Rlelease\__ folder ( the \*.dll files) in the zip file should be copied to __c:\Program Files\opendtect\bin\win64\Release\__; and
- the contents of __plugins\win64\__ folder ( the \*.alo files) in the zip file should be copied to __c:\Program Files\opendtect\plugins\win64\__

The /*.alo files are needed to autoload the plugins.

As an alternative to installing in the OpendTect folder you can set up a separate folder for the plugins and point to it using the __OD_USER_PLUGIN_DIR__ environment variable as per [these instructions](http://waynegm.github.io/OpendTect-Plugin-Docs/Installation/faq/). I actually prefer this method because I'm not sure if the OpendTect installation manager preserves foreign files during updates and it also provides a way to use the plugins with multiple versions of OpendTect.

Let me know if that helps.

**Comment by jobar8** [comment]
Thanks Wayne. I did not realise I had to copy the .alo files as well... probably because it is not mentioned in your [instructions] (http://waynegm.github.io/OpendTect-Plugin-Wiki/en/#!pages/installation.md) in the Windows > Sitewide Installation section. 
Cheers.

**Comment by waynegm** [comment]
Good you got it working. Yeh I better add that to the docs.
